/**
 * Curated baseline — classic edit techniques + SFX that stay relevant.
 * These are ALWAYS included in the feed. Exa discoveries augment but don't replace.
 *
 * Add/edit entries here to expand the baseline. Each entry will be enriched
 * with exampleSetup if missing via the backfill step.
 */

export const SEED_SFX = [
  {
    type: 'sfx',
    name: 'FAH inhale',
    category: 'audio-accent',
    description: 'Quick sharp inhale sound used as a dramatic gasp or realisation moment.',
    vibe: 'dramatic · reactive · gen-Z humour',
    whenToUse: [
      'right before a reveal or plot-twist',
      'reaction content — signalling shock',
      'opening frame as a hook-grab',
    ],
    exampleSetup: 'Import FAH sfx clip in CapCut or Premiere. Place it 0.2s before your visual punchline — so the inhale lands, then the cut/reveal happens on the sudden silence after.',
    pairsWellWith: ['freeze frame', 'zoom punch-in', 'text reveal'],
    toolsNeeded: ['CapCut', 'Premiere', 'native TikTok editor'],
    difficulty: 'easy',
    creatorArchetypes: ['comedy', 'reaction', 'storytime', 'lifestyle'],
    sourceHint: 'Evergreen TikTok SFX — one of the most-used reaction sounds since 2023',
  },
  {
    type: 'sfx',
    name: 'Vine Boom',
    category: 'audio-accent',
    description: 'Heavy bass thud used to emphasise a punchline or mic-drop moment.',
    vibe: 'punchy · comedic · ironic',
    whenToUse: [
      'after a comedic statement as a laugh-track replacement',
      'reveal of an absurd fact or take',
      'meme-style emphasis on specific text',
    ],
    exampleSetup: 'Drop the Vine Boom exactly on frame with the punchline word. Works best when muted under 1s — fire it as a stinger, not a sustain.',
    pairsWellWith: ['text pop-up', 'zoom punch-in', 'FAH inhale'],
    toolsNeeded: ['CapCut', 'Premiere', 'native TikTok editor'],
    difficulty: 'easy',
    creatorArchetypes: ['comedy', 'B2B', 'lifestyle', 'commentary'],
    sourceHint: 'Evergreen — the meme SFX that refuses to die',
  },
  {
    type: 'sfx',
    name: 'Record scratch + freeze',
    category: 'audio-accent',
    description: 'DJ scratch sound paired with a hard stop / freeze-frame on an unexpected beat.',
    vibe: 'self-aware · breaking-the-fourth-wall',
    whenToUse: [
      '"yep, that\'s me. you\'re probably wondering…" opening',
      'mid-video pattern interrupt when things get weird',
      'before dropping an unexpected take',
    ],
    exampleSetup: 'On the moment you want to interrupt the flow, freeze the frame for 1-2s and layer the record scratch on frame 1 of the freeze. Optional: add a sticker or caption during the freeze.',
    pairsWellWith: ['freeze frame', 'text overlay', 'voiceover narration'],
    toolsNeeded: ['CapCut', 'Premiere'],
    difficulty: 'easy',
    creatorArchetypes: ['storytime', 'comedy', 'educator', 'lifestyle'],
    sourceHint: 'Evergreen — classic storytime opener',
  },
  {
    type: 'sfx',
    name: 'Oh My God Becky',
    category: 'audio-accent',
    description: 'Recycled Sir Mix-a-Lot spoken intro used as a dramatic "look at this" cue.',
    vibe: 'comedic · dramatic · millennial-nostalgia',
    whenToUse: [
      'showing something absurd or jaw-dropping',
      'reaction to a visual reveal',
      'pointing at someone else\'s content',
    ],
    exampleSetup: 'Start the sound 0.5s before you show the thing to react to. Hold a shocked facial expression until "…look at her butt" finishes, then cut to the payoff.',
    pairsWellWith: ['point-of-view shot', 'split-screen reaction', 'zoom punch-in'],
    toolsNeeded: ['CapCut', 'native TikTok editor'],
    difficulty: 'easy',
    creatorArchetypes: ['comedy', 'reaction', 'commentary', 'lifestyle'],
    sourceHint: 'Evergreen — endless meme reuse since 2021',
  },
  {
    type: 'sfx',
    name: 'Anime subway run',
    category: 'audio-accent',
    description: 'Japanese train-station speed ambient sound used behind montage or sprint clips.',
    vibe: 'fast-paced · urgent · anime-core',
    whenToUse: [
      '"rush to get ready" montages',
      'hustle / grind content',
      'transitions between multiple quick tasks',
    ],
    exampleSetup: 'Use under a 3-5 shot montage with each clip 0.6-0.8s long. Cut on every beat of the subway door chime. End on a clean hard-cut to normal ambience.',
    pairsWellWith: ['speed ramp', 'whip pan', 'jump cut stack'],
    toolsNeeded: ['CapCut', 'Premiere'],
    difficulty: 'moderate',
    creatorArchetypes: ['lifestyle', 'fitness', 'productivity', 'storytime'],
    sourceHint: 'Evergreen Gen-Z staple',
  },
  {
    type: 'sfx',
    name: 'Text-pop ding',
    category: 'audio-accent',
    description: 'Short bell/pop sound that plays when text captions appear on screen.',
    vibe: 'clean · clinical · educational',
    whenToUse: [
      'each new text overlay appearing',
      'numbered list reveal (1, 2, 3 with dings)',
      'emphasising a statistic or pull-quote',
    ],
    exampleSetup: 'Sync the pop exactly on frame with text fade-in (duration ~0.15s). Use the same sound for every text in a video so it becomes rhythmic.',
    pairsWellWith: ['text overlay', 'numbered-list carousel style'],
    toolsNeeded: ['CapCut', 'Premiere', 'native TikTok editor'],
    difficulty: 'easy',
    creatorArchetypes: ['educator', 'B2B', 'explainer', 'how-to'],
    sourceHint: 'Evergreen — the B2B + educational SFX of choice',
  },
  {
    type: 'sfx',
    name: 'Sparkle chime',
    category: 'audio-accent',
    description: 'Magical sparkle sound marking a transformation or reveal moment.',
    vibe: 'magical · aspirational · soft',
    whenToUse: [
      'before/after transformation reveal',
      'product unveiling',
      'outfit change transition',
    ],
    exampleSetup: 'Layer the sparkle starting 0.3s before the visual change, peaking exactly on the reveal frame. Hold the reveal static for 1-1.5s while the sparkle fades.',
    pairsWellWith: ['invisible transition', 'match cut', 'zoom out'],
    toolsNeeded: ['CapCut', 'Premiere'],
    difficulty: 'easy',
    creatorArchetypes: ['beauty', 'fashion', 'home decor', 'lifestyle'],
    sourceHint: 'Evergreen transformation staple',
  },
  {
    type: 'sfx',
    name: 'Bass drop stinger',
    category: 'audio-accent',
    description: 'Sudden low-end hit that lands on a beat drop or visual reveal.',
    vibe: 'impactful · hype · club-energy',
    whenToUse: [
      'dramatic reveal on beat',
      'intense moment punctuation',
      'transition between hype sections',
    ],
    exampleSetup: 'Align the bass drop with your hardest visual cut. Duck ambient audio 0.2s before the drop so the bass lands in silence, then resume full audio.',
    pairsWellWith: ['speed ramp', 'zoom punch-in', 'flash transition'],
    toolsNeeded: ['CapCut', 'Premiere'],
    difficulty: 'moderate',
    creatorArchetypes: ['fitness', 'fashion', 'hype creator'],
    sourceHint: 'Evergreen — the universal "something big just happened" SFX',
  },
];

export const SEED_EDITS = [
  {
    type: 'edit',
    name: 'Invisible transition',
    category: 'transition',
    description: 'Seamless cut that hides the edit by matching motion, framing, or object position.',
    vibe: 'slick · magical · satisfying',
    whenToUse: [
      'outfit changes',
      'location jumps',
      'product reveals',
    ],
    exampleSetup: 'Frame the last 10% of the outgoing shot identically to the first 10% of the incoming shot (same position, same lighting). Cut on motion — e.g. hand swipe across camera. Use J-cut to carry audio across.',
    pairsWellWith: ['sparkle chime', 'whip pan', 'match cut'],
    toolsNeeded: ['CapCut', 'Premiere', 'DaVinci'],
    difficulty: 'moderate',
    creatorArchetypes: ['fashion', 'beauty', 'lifestyle', 'storytime'],
    sourceHint: 'Core short-form technique — still dominates 2026 feeds',
  },
  {
    type: 'edit',
    name: 'Zoom punch-in',
    category: 'reveal',
    description: 'Rapid scale-up on the subject to emphasise a key word or expression.',
    vibe: 'punchy · attention-grabbing · dramatic',
    whenToUse: [
      'on a specific word in voiceover',
      'reacting to a surprise',
      'emphasising a number or stat',
    ],
    exampleSetup: 'Keyframe scale from 100% to 130% over 3-5 frames, hold for 1s, snap back. Add 1-2px shake. Layer Vine Boom or impact SFX on the peak frame.',
    pairsWellWith: ['Vine Boom', 'text pop', 'speed ramp'],
    toolsNeeded: ['CapCut', 'Premiere'],
    difficulty: 'easy',
    creatorArchetypes: ['comedy', 'educator', 'B2B', 'reaction'],
    sourceHint: 'Universal punctuation move — never gets old',
  },
  {
    type: 'edit',
    name: 'Speed ramp',
    category: 'pacing',
    description: 'Dynamic change in playback speed — typically slow → fast or fast → slow on beat.',
    vibe: 'cinematic · rhythmic · premium',
    whenToUse: [
      'transitioning into a reveal',
      'emphasising a hit or landing',
      'matching a beat drop',
    ],
    exampleSetup: 'Use CapCut\'s Curve Speed → "Montage" or "Hero Moment" preset. Start at 0.3×, ramp to 2× over 0.5s, ramp back to 1× on beat.',
    pairsWellWith: ['bass drop stinger', 'whip pan', 'match cut'],
    toolsNeeded: ['CapCut', 'Premiere'],
    difficulty: 'moderate',
    creatorArchetypes: ['fitness', 'lifestyle', 'fashion', 'travel'],
    sourceHint: 'Classic cinematographer move translated to short-form',
  },
  {
    type: 'edit',
    name: 'Jump cut stack',
    category: 'pacing',
    description: 'Rapid succession of hard cuts on same framing to compress time or energy.',
    vibe: 'chaotic · fast · comedic',
    whenToUse: [
      'explainer videos — compressing multiple takes',
      'showing repetition (eating, trying on outfits)',
      'building mid-video energy',
    ],
    exampleSetup: 'Record the same shot 4-6 times with subtle variations. Cut ruthlessly — each shot 0.6-1s max. Keep continuous audio to smooth the visual chaos.',
    pairsWellWith: ['anime subway', 'whip pan'],
    toolsNeeded: ['CapCut', 'Premiere', 'DaVinci'],
    difficulty: 'easy',
    creatorArchetypes: ['educator', 'B2B', 'comedy', 'storytime'],
    sourceHint: 'Foundational short-form pacing technique',
  },
  {
    type: 'edit',
    name: 'Freeze frame + caption',
    category: 'reveal',
    description: 'Pause on a key frame with text overlay to deliver a point.',
    vibe: 'emphatic · educational · pausing-for-effect',
    whenToUse: [
      'delivering a statistic',
      'making a definitive claim',
      'pattern-interrupt mid-action',
    ],
    exampleSetup: 'Freeze on the frame where the subject\'s expression lands hardest. Hold 1.5-2s. Add centred caption in bold white text with drop-shadow. Resume playback with a visible hard cut.',
    pairsWellWith: ['record scratch', 'text-pop ding', 'zoom punch-in'],
    toolsNeeded: ['CapCut', 'Premiere'],
    difficulty: 'easy',
    creatorArchetypes: ['educator', 'storytime', 'B2B', 'commentary'],
    sourceHint: 'The pattern-interrupt workhorse',
  },
  {
    type: 'edit',
    name: 'Split-screen reaction',
    category: 'reveal',
    description: 'Dual-panel showing source content on one side, reaction/commentary on the other.',
    vibe: 'conversational · reactive · comedic',
    whenToUse: [
      'reacting to viral content',
      'commentary / review content',
      'compare-contrast teaching',
    ],
    exampleSetup: 'Split frame 50/50 vertically. Source content left, you right (face-cam). Mute source during your reactions to keep attention. Add subtle inward-lean animation during key moments.',
    pairsWellWith: ['Oh My God Becky', 'FAH inhale', 'zoom punch-in'],
    toolsNeeded: ['CapCut', 'Premiere'],
    difficulty: 'moderate',
    creatorArchetypes: ['reaction', 'commentary', 'educator'],
    sourceHint: 'Reaction-content staple',
  },
  {
    type: 'edit',
    name: 'Whip pan transition',
    category: 'transition',
    description: 'Fast horizontal or vertical pan to mask a cut between scenes.',
    vibe: 'kinetic · energetic · cinematic',
    whenToUse: [
      'location changes',
      'mid-sentence topic pivots',
      'montage transitions',
    ],
    exampleSetup: 'End outgoing shot with a fast pan right. Start incoming shot with a pan right already at matching speed. Blur both ends by 4-8 pixels. Layer a swoosh or anime-subway SFX during the blur.',
    pairsWellWith: ['anime subway', 'speed ramp'],
    toolsNeeded: ['CapCut', 'Premiere'],
    difficulty: 'moderate',
    creatorArchetypes: ['travel', 'lifestyle', 'fitness', 'storytime'],
    sourceHint: 'Classic cinematic move, evergreen in short-form',
  },
  {
    type: 'edit',
    name: 'Text-overlay storytime',
    category: 'text-overlay',
    description: 'Full-screen or prominent captions carrying the narrative while B-roll plays.',
    vibe: 'confessional · accessible · algorithm-friendly',
    whenToUse: [
      'storytime content',
      'no-face vlogs',
      'silent-friendly content for autoplay feeds',
    ],
    exampleSetup: 'Break narrative into 8-12 word chunks. Display each chunk for 1.5-2s centred with white text + black stroke. Animate each chunk in with a tiny scale pop (1.0 → 1.05 → 1.0).',
    pairsWellWith: ['text-pop ding', 'freeze frame'],
    toolsNeeded: ['CapCut', 'native TikTok editor'],
    difficulty: 'easy',
    creatorArchetypes: ['storytime', 'educator', 'B2B', 'lifestyle'],
    sourceHint: 'Dominant short-form format — autoplay muted is default',
  },
];

export function allSeeds() {
  return [...SEED_SFX, ...SEED_EDITS];
}
